### ISSUE TITLE
connect TweetStream error?

### ISSUE THREAD

**Issue by dmnlk** [hiroakis/twslacker#2]
full log

```

$ bundle exec ruby bin/twslacker start --ignore=RT --type track Twitter
/home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:403:in `start'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:136:in `filter'
        from /home/dmnlk/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:105:in `track'
        from /home/dmnlk/twslacker/lib/twslacker/twitter_client.rb:38:in `track'
        from /home/dmnlk/lib/twslacker/base.rb:51:in `run'
        from bin/twslacker:9:in `<main>'

```

**Comment by hiroakis** [comment]
@dmnlk I confirmed your command on my server. The command works well. Could you recheck?

<img width="913" alt="screen" src="https://cloud.githubusercontent.com/assets/621569/8515102/13d64512-23d7-11e5-8ab4-06e586218cfb.png">

**Comment by dmnlk** [comment]
I regenerated AccessToken,work correctly thanks
